// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProgramlamaOdev.Data;

#nullable disable

namespace WebProgramlamaOdev.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Height")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Weight")
                        .IsRequired()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Erkek",
                            Height = 180,
                            UserId = "member-001",
                            Weight = 75.5m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1998, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Kadın",
                            Height = 165,
                            UserId = "member-002",
                            Weight = 58.0m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1992, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Erkek",
                            Height = 175,
                            UserId = "member-003",
                            Weight = 80.0m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ServiceType_IsActive");

                    b.HasIndex("TrainerId");

                    b.ToTable("ServiceType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Birebir kişisel antrenman seansı. Antrenörünüz sizin için özel program hazırlar.",
                            Duration = 60,
                            GymId = 1,
                            IsActive = true,
                            Name = "Kişisel Antrenman",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Grup halinde pilates antrenmanı. Maksimum 10 kişilik gruplar.",
                            Duration = 45,
                            GymId = 1,
                            IsActive = true,
                            Name = "Grup Dersi - Pilates",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Diyet ve beslenme programı oluşturma. Kişiye özel beslenme planı.",
                            Duration = 30,
                            GymId = 1,
                            IsActive = true,
                            Name = "Beslenme Danışmanlığı",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Yüksek tempolu kardiyo antrenmanı. Maksimum 15 kişilik gruplar.",
                            Duration = 45,
                            GymId = 1,
                            IsActive = true,
                            Name = "Grup Dersi - Spinning",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nefes egzersizleri ve esneme hareketleri ile zihin ve beden dinginliği.",
                            Duration = 60,
                            GymId = 1,
                            IsActive = true,
                            Name = "Yoga",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Yüksek yoğunluklu fonksiyonel antrenman",
                            Duration = 60,
                            GymId = 2,
                            IsActive = true,
                            Name = "Crossfit",
                            Price = 180.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dayanıklılık ve kondisyon geliştirme",
                            Duration = 45,
                            GymId = 2,
                            IsActive = true,
                            Name = "Kardio Antrenmanı",
                            Price = 130.00m
                        });
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.AIDailyPlanRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GeneratedImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_AIRecommendation_Member");

                    b.ToTable("AIDailyPlanRecommendations");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "61c035e9-c74e-4c0e-a213-62a99e5dc165",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gym.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GYM.COM",
                            NormalizedUserName = "ADMIN@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELqP9QqP0yH8XxJHLKJv3xK+5xL6Y3sR8vN9wT4mP2xQ7zR1sK0vB5nM3cL9dT6eA==",
                            PhoneNumber = "05551234567",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3836e5fa-b84e-462e-834e-789f93d4fde2",
                            TwoFactorEnabled = false,
                            UserName = "admin@gym.com",
                            UserType = "Admin"
                        },
                        new
                        {
                            Id = "gym-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0e711bfe-ff28-4fe4-bd24-bc2bdc756da6",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sakarya@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Gym",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "SAKARYA@GYM.COM",
                            NormalizedUserName = "SAKARYA@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELqP9QqP0yH8XxJHLKJv3xK+5xL6Y3sR8vN9wT4mP2xQ7zR1sK0vB5nM3cL9dT6eA==",
                            PhoneNumber = "05551112233",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b03b5d46-77c0-44a6-abfd-513965b6f5ad",
                            TwoFactorEnabled = false,
                            UserName = "sakarya@gym.com",
                            UserType = "Gym"
                        },
                        new
                        {
                            Id = "gym-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57634f8e-15f8-4155-b388-d62c65595506",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adapazari@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Gym",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADAPAZARI@GYM.COM",
                            NormalizedUserName = "ADAPAZARI@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELqP9QqP0yH8XxJHLKJv3xK+5xL6Y3sR8vN9wT4mP2xQ7zR1sK0vB5nM3cL9dT6eA==",
                            PhoneNumber = "05559998877",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8d07e10-ff83-4197-b848-3ad0b1553109",
                            TwoFactorEnabled = false,
                            UserName = "adapazari@gym.com",
                            UserType = "Gym"
                        },
                        new
                        {
                            Id = "trainer-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe116134-cff5-46ee-a224-f666021bdcdd",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmet.yilmaz@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmet",
                            LastName = "Yılmaz",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMET.YILMAZ@GYM.COM",
                            NormalizedUserName = "AHMET.YILMAZ@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELqP9QqP0yH8XxJHLKJv3xK+5xL6Y3sR8vN9wT4mP2xQ7zR1sK0vB5nM3cL9dT6eA==",
                            PhoneNumber = "05551234501",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "96b0a302-1388-4568-9dc1-3743f9ad746d",
                            TwoFactorEnabled = false,
                            UserName = "ahmet.yilmaz@gym.com",
                            UserType = "Trainer"
                        },
                        new
                        {
                            Id = "trainer-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8654c29c-198f-4b8f-8d42-bd3cc9fbd2fd",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mehmet.demir@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Mehmet",
                            LastName = "Demir",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEHMET.DEMIR@GYM.COM",
                            NormalizedUserName = "MEHMET.DEMIR@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELqP9QqP0yH8XxJHLKJv3xK+5xL6Y3sR8vN9wT4mP2xQ7zR1sK0vB5nM3cL9dT6eA==",
                            PhoneNumber = "05551234502",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f7471a13-43b2-480f-ae7f-60aa16751c4c",
                            TwoFactorEnabled = false,
                            UserName = "mehmet.demir@gym.com",
                            UserType = "Trainer"
                        },
                        new
                        {
                            Id = "trainer-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ee2a550-55cf-4091-bbca-8fcf4b0cb142",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayse.kara@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Ayşe",
                            LastName = "Kara",
                            LockoutEnabled = false,
                            NormalizedEmail = "AYSE.KARA@GYM.COM",
                            NormalizedUserName = "AYSE.KARA@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELqP9QqP0yH8XxJHLKJv3xK+5xL6Y3sR8vN9wT4mP2xQ7zR1sK0vB5nM3cL9dT6eA==",
                            PhoneNumber = "05551234503",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a455e26-6b06-4bd4-b14f-b1b25c92f622",
                            TwoFactorEnabled = false,
                            UserName = "ayse.kara@gym.com",
                            UserType = "Trainer"
                        },
                        new
                        {
                            Id = "member-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fbb81d9f-13db-4853-aee4-f7b37bdd3c05",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.veli@test.com",
                            EmailConfirmed = true,
                            FirstName = "Ali",
                            LastName = "Veli",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI.VELI@TEST.COM",
                            NormalizedUserName = "ALI.VELI@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELqP9QqP0yH8XxJHLKJv3xK+5xL6Y3sR8vN9wT4mP2xQ7zR1sK0vB5nM3cL9dT6eA==",
                            PhoneNumber = "05559876501",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e1e98c42-763a-42bd-915f-179999fe12f9",
                            TwoFactorEnabled = false,
                            UserName = "ali.veli@test.com",
                            UserType = "Member"
                        },
                        new
                        {
                            Id = "member-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cefe08ab-3f2c-4096-9076-97a353410581",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zeynep.can@test.com",
                            EmailConfirmed = true,
                            FirstName = "Zeynep",
                            LastName = "Can",
                            LockoutEnabled = false,
                            NormalizedEmail = "ZEYNEP.CAN@TEST.COM",
                            NormalizedUserName = "ZEYNEP.CAN@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELqP9QqP0yH8XxJHLKJv3xK+5xL6Y3sR8vN9wT4mP2xQ7zR1sK0vB5nM3cL9dT6eA==",
                            PhoneNumber = "05559876502",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82dfbcaa-9bae-47b7-8b81-08c302091598",
                            TwoFactorEnabled = false,
                            UserName = "zeynep.can@test.com",
                            UserType = "Member"
                        },
                        new
                        {
                            Id = "member-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f695dd09-d5ec-4397-949f-c73d5d602991",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "can.ozturk@test.com",
                            EmailConfirmed = true,
                            FirstName = "Can",
                            LastName = "Öztürk",
                            LockoutEnabled = false,
                            NormalizedEmail = "CAN.OZTURK@TEST.COM",
                            NormalizedUserName = "CAN.OZTURK@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELqP9QqP0yH8XxJHLKJv3xK+5xL6Y3sR8vN9wT4mP2xQ7zR1sK0vB5nM3cL9dT6eA==",
                            PhoneNumber = "05559876503",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c9c4044a-40af-4fef-9145-33ada55e8cc7",
                            TwoFactorEnabled = false,
                            UserName = "can.ozturk@test.com",
                            UserType = "Member"
                        });
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Appointment_Status");

                    b.HasIndex("TrainerId", "AppointmentDate", "StartTime")
                        .HasDatabaseName("IX_Appointment_Trainer_Date_Time");

                    b.ToTable("Appointment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedDate = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            IsConfirmed = true,
                            MemberId = 1,
                            ServiceTypeId = 1,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Status = "Confirmed",
                            TotalPrice = 200.00m,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            EndTime = new TimeSpan(0, 11, 45, 0, 0),
                            IsConfirmed = false,
                            MemberId = 2,
                            ServiceTypeId = 2,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            Status = "Pending",
                            TotalPrice = 100.00m,
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Gyms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sakarya Üniversitesi Esentepe Kampüsü, Serdivan/Sakarya",
                            ClosingTime = new TimeSpan(0, 23, 0, 0, 0),
                            IsActive = true,
                            Name = "Sakarya Fitness Center",
                            OpeningTime = new TimeSpan(0, 6, 0, 0, 0),
                            UserId = "gym-001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Merkez Mah. Atatürk Cad. No:123, Adapazarı/Sakarya",
                            ClosingTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsActive = true,
                            Name = "Adapazarı Spor Salonu",
                            OpeningTime = new TimeSpan(0, 7, 0, 0, 0),
                            UserId = "gym-002"
                        });
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.ServicesByTrainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("TrainerId");

                    b.ToTable("ServicesByTrainer");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ServiceTypeId = 1,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = -2,
                            ServiceTypeId = 3,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = -3,
                            ServiceTypeId = 2,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = -4,
                            ServiceTypeId = 5,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = -5,
                            ServiceTypeId = 6,
                            TrainerId = 3
                        },
                        new
                        {
                            Id = -6,
                            ServiceTypeId = 7,
                            TrainerId = 3
                        });
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Trainer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GymId = 1,
                            IsActive = true,
                            Specialization = "Kişisel Antrenman, Güç Antrenmanı",
                            UserId = "trainer-001"
                        },
                        new
                        {
                            Id = 2,
                            GymId = 1,
                            IsActive = true,
                            Specialization = "Pilates, Yoga, Esneklik",
                            UserId = "trainer-002"
                        },
                        new
                        {
                            Id = 3,
                            GymId = 2,
                            IsActive = true,
                            Specialization = "Crossfit, Fonksiyonel Antrenman",
                            UserId = "trainer-003"
                        });
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.TrainerAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId", "EventDate")
                        .HasDatabaseName("IX_TrainerAvailability_Trainer_Date");

                    b.ToTable("TrainerAvailability");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            EventDate = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            EventDate = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            EventDate = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            EventDate = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            EventDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            EventDate = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            TrainerId = 3
                        });
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.HasOne("WebProgramlamaOdev.Models.ApplicationUser", "User")
                        .WithOne("Member")
                        .HasForeignKey("Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebProgramlamaOdev.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebProgramlamaOdev.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebProgramlamaOdev.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebProgramlamaOdev.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceType", b =>
                {
                    b.HasOne("WebProgramlamaOdev.Models.Gym", "Gym")
                        .WithMany("ServiceList")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebProgramlamaOdev.Models.Trainer", null)
                        .WithMany("TrainerServiceTypes")
                        .HasForeignKey("TrainerId");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.AIDailyPlanRecommendation", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("AIRecommendations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.Appointment", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("Appointments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceType", "ServiceType")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebProgramlamaOdev.Models.Trainer", "Trainer")
                        .WithMany("Appointments")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("ServiceType");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.Gym", b =>
                {
                    b.HasOne("WebProgramlamaOdev.Models.ApplicationUser", "User")
                        .WithOne("Gym")
                        .HasForeignKey("WebProgramlamaOdev.Models.Gym", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.ServicesByTrainer", b =>
                {
                    b.HasOne("ServiceType", "serviceType")
                        .WithMany("ServicesByTrainers")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebProgramlamaOdev.Models.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trainer");

                    b.Navigation("serviceType");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.Trainer", b =>
                {
                    b.HasOne("WebProgramlamaOdev.Models.Gym", "Gym")
                        .WithMany("TrainerList")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebProgramlamaOdev.Models.ApplicationUser", "User")
                        .WithOne("Trainer")
                        .HasForeignKey("WebProgramlamaOdev.Models.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.TrainerAvailability", b =>
                {
                    b.HasOne("WebProgramlamaOdev.Models.Trainer", "Trainer")
                        .WithMany("Availabilities")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.Navigation("AIRecommendations");

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ServiceType", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServicesByTrainers");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.ApplicationUser", b =>
                {
                    b.Navigation("Gym");

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.Gym", b =>
                {
                    b.Navigation("ServiceList");

                    b.Navigation("TrainerList");
                });

            modelBuilder.Entity("WebProgramlamaOdev.Models.Trainer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");

                    b.Navigation("TrainerServiceTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
